/**
 * @fileoverview gRPC-Web generated client stub for ondewo.vtsi
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: ondewo/vtsi/campaigns.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var ondewo_sip_sip_pb = require('../../ondewo/sip/sip_pb.js')
const proto = {};
proto.ondewo = {};
proto.ondewo.vtsi = require('./campaigns_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ondewo.vtsi.CampaignsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ondewo.vtsi.CampaignsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.CreateCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_CreateCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/CreateCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.CreateCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.CreateCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.CreateCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.createCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/CreateCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_CreateCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.CreateCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.createCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/CreateCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_CreateCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.GetCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_GetCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/GetCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.GetCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.GetCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.GetCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.getCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/GetCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_GetCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.GetCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.getCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/GetCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_GetCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.UpdateCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_UpdateCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/UpdateCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.UpdateCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.UpdateCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.UpdateCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.updateCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/UpdateCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_UpdateCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.UpdateCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.updateCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/UpdateCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_UpdateCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.DeleteCampaignRequest,
 *   !proto.ondewo.vtsi.DeleteCampaignResponse>}
 */
const methodDescriptor_Campaigns_DeleteCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/DeleteCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.DeleteCampaignRequest,
  proto.ondewo.vtsi.DeleteCampaignResponse,
  /**
   * @param {!proto.ondewo.vtsi.DeleteCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.DeleteCampaignResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.DeleteCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.DeleteCampaignResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.DeleteCampaignResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.deleteCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/DeleteCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_DeleteCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.DeleteCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.DeleteCampaignResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.deleteCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/DeleteCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_DeleteCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ListCampaignsRequest,
 *   !proto.ondewo.vtsi.ListCampaignsResponse>}
 */
const methodDescriptor_Campaigns_ListCampaigns = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/ListCampaigns',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ListCampaignsRequest,
  proto.ondewo.vtsi.ListCampaignsResponse,
  /**
   * @param {!proto.ondewo.vtsi.ListCampaignsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.ListCampaignsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ListCampaignsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.ListCampaignsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.ListCampaignsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.listCampaigns =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/ListCampaigns',
      request,
      metadata || {},
      methodDescriptor_Campaigns_ListCampaigns,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ListCampaignsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.ListCampaignsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.listCampaigns =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/ListCampaigns',
      request,
      metadata || {},
      methodDescriptor_Campaigns_ListCampaigns);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.GetCampaignStatisticsRequest,
 *   !proto.ondewo.vtsi.CampaignStatistics>}
 */
const methodDescriptor_Campaigns_GetCampaignStatistics = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/GetCampaignStatistics',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.GetCampaignStatisticsRequest,
  proto.ondewo.vtsi.CampaignStatistics,
  /**
   * @param {!proto.ondewo.vtsi.GetCampaignStatisticsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.CampaignStatistics.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.GetCampaignStatisticsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.CampaignStatistics)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.CampaignStatistics>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.getCampaignStatistics =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/GetCampaignStatistics',
      request,
      metadata || {},
      methodDescriptor_Campaigns_GetCampaignStatistics,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.GetCampaignStatisticsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.CampaignStatistics>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.getCampaignStatistics =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/GetCampaignStatistics',
      request,
      metadata || {},
      methodDescriptor_Campaigns_GetCampaignStatistics);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ListCampaignCallsRequest,
 *   !proto.ondewo.vtsi.ListCampaignCallsResponse>}
 */
const methodDescriptor_Campaigns_ListCampaignCalls = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/ListCampaignCalls',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ListCampaignCallsRequest,
  proto.ondewo.vtsi.ListCampaignCallsResponse,
  /**
   * @param {!proto.ondewo.vtsi.ListCampaignCallsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.ListCampaignCallsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ListCampaignCallsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.ListCampaignCallsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.ListCampaignCallsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.listCampaignCalls =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/ListCampaignCalls',
      request,
      metadata || {},
      methodDescriptor_Campaigns_ListCampaignCalls,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ListCampaignCallsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.ListCampaignCallsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.listCampaignCalls =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/ListCampaignCalls',
      request,
      metadata || {},
      methodDescriptor_Campaigns_ListCampaignCalls);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.StartCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_StartCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/StartCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.StartCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.StartCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.StartCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.startCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/StartCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_StartCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.StartCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.startCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/StartCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_StartCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.StopCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_StopCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/StopCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.StopCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.StopCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.StopCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.stopCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/StopCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_StopCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.StopCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.stopCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/StopCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_StopCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.HardStopCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_HardStopCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/HardStopCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.HardStopCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.HardStopCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.HardStopCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.hardStopCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/HardStopCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_HardStopCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.HardStopCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.hardStopCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/HardStopCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_HardStopCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ResumeCampaignRequest,
 *   !proto.ondewo.vtsi.Campaign>}
 */
const methodDescriptor_Campaigns_ResumeCampaign = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/ResumeCampaign',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ResumeCampaignRequest,
  proto.ondewo.vtsi.Campaign,
  /**
   * @param {!proto.ondewo.vtsi.ResumeCampaignRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.Campaign.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ResumeCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.Campaign)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.Campaign>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.resumeCampaign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/ResumeCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_ResumeCampaign,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ResumeCampaignRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.Campaign>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.resumeCampaign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Campaigns/ResumeCampaign',
      request,
      metadata || {},
      methodDescriptor_Campaigns_ResumeCampaign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.StreamCampaignStatusRequest,
 *   !proto.ondewo.vtsi.StreamCampaignStatusResponse>}
 */
const methodDescriptor_Campaigns_StreamCampaignStatus = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Campaigns/StreamCampaignStatus',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.ondewo.vtsi.StreamCampaignStatusRequest,
  proto.ondewo.vtsi.StreamCampaignStatusResponse,
  /**
   * @param {!proto.ondewo.vtsi.StreamCampaignStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.StreamCampaignStatusResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.StreamCampaignStatusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.StreamCampaignStatusResponse>}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsClient.prototype.streamCampaignStatus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ondewo.vtsi.Campaigns/StreamCampaignStatus',
      request,
      metadata || {},
      methodDescriptor_Campaigns_StreamCampaignStatus);
};


/**
 * @param {!proto.ondewo.vtsi.StreamCampaignStatusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.StreamCampaignStatusResponse>}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.CampaignsPromiseClient.prototype.streamCampaignStatus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ondewo.vtsi.Campaigns/StreamCampaignStatus',
      request,
      metadata || {},
      methodDescriptor_Campaigns_StreamCampaignStatus);
};


module.exports = proto.ondewo.vtsi;

