/**
 * @fileoverview gRPC-Web generated client stub for ondewo.vtsi
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: ondewo/vtsi/logs.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var ondewo_nlu_common_pb = require('../../ondewo/nlu/common_pb.js')

var ondewo_vtsi_calls_pb = require('../../ondewo/vtsi/calls_pb.js')
const proto = {};
proto.ondewo = {};
proto.ondewo.vtsi = require('./logs_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ondewo.vtsi.LogsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ondewo.vtsi.LogsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.StreamCallLogsRequest,
 *   !proto.ondewo.vtsi.StreamCallLogsResponse>}
 */
const methodDescriptor_Logs_StreamCallLogs = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Logs/StreamCallLogs',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.ondewo.vtsi.StreamCallLogsRequest,
  proto.ondewo.vtsi.StreamCallLogsResponse,
  /**
   * @param {!proto.ondewo.vtsi.StreamCallLogsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.StreamCallLogsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.StreamCallLogsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.StreamCallLogsResponse>}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.LogsClient.prototype.streamCallLogs =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ondewo.vtsi.Logs/StreamCallLogs',
      request,
      metadata || {},
      methodDescriptor_Logs_StreamCallLogs);
};


/**
 * @param {!proto.ondewo.vtsi.StreamCallLogsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.StreamCallLogsResponse>}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.LogsPromiseClient.prototype.streamCallLogs =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ondewo.vtsi.Logs/StreamCallLogs',
      request,
      metadata || {},
      methodDescriptor_Logs_StreamCallLogs);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ListCallLogsRequest,
 *   !proto.ondewo.vtsi.ListCallLogsResponse>}
 */
const methodDescriptor_Logs_ListCallLogs = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Logs/ListCallLogs',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ListCallLogsRequest,
  proto.ondewo.vtsi.ListCallLogsResponse,
  /**
   * @param {!proto.ondewo.vtsi.ListCallLogsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.ListCallLogsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ListCallLogsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.ListCallLogsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.ListCallLogsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.LogsClient.prototype.listCallLogs =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Logs/ListCallLogs',
      request,
      metadata || {},
      methodDescriptor_Logs_ListCallLogs,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ListCallLogsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.ListCallLogsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.LogsPromiseClient.prototype.listCallLogs =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Logs/ListCallLogs',
      request,
      metadata || {},
      methodDescriptor_Logs_ListCallLogs);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.GetCallLogStreamRequest,
 *   !proto.ondewo.vtsi.CallLogStream>}
 */
const methodDescriptor_Logs_GetCallLogStream = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Logs/GetCallLogStream',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.GetCallLogStreamRequest,
  proto.ondewo.vtsi.CallLogStream,
  /**
   * @param {!proto.ondewo.vtsi.GetCallLogStreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.CallLogStream.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.GetCallLogStreamRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.CallLogStream)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.CallLogStream>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.LogsClient.prototype.getCallLogStream =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Logs/GetCallLogStream',
      request,
      metadata || {},
      methodDescriptor_Logs_GetCallLogStream,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.GetCallLogStreamRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.CallLogStream>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.LogsPromiseClient.prototype.getCallLogStream =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Logs/GetCallLogStream',
      request,
      metadata || {},
      methodDescriptor_Logs_GetCallLogStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ListCallLogStreamsRequest,
 *   !proto.ondewo.vtsi.ListCallLogStreamsResponse>}
 */
const methodDescriptor_Logs_ListCallLogStreams = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Logs/ListCallLogStreams',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ListCallLogStreamsRequest,
  proto.ondewo.vtsi.ListCallLogStreamsResponse,
  /**
   * @param {!proto.ondewo.vtsi.ListCallLogStreamsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.ListCallLogStreamsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ListCallLogStreamsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.ListCallLogStreamsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.ListCallLogStreamsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.LogsClient.prototype.listCallLogStreams =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Logs/ListCallLogStreams',
      request,
      metadata || {},
      methodDescriptor_Logs_ListCallLogStreams,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ListCallLogStreamsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.ListCallLogStreamsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.LogsPromiseClient.prototype.listCallLogStreams =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Logs/ListCallLogStreams',
      request,
      metadata || {},
      methodDescriptor_Logs_ListCallLogStreams);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.DeleteCallLogsRequest,
 *   !proto.ondewo.vtsi.DeleteCallLogsResponse>}
 */
const methodDescriptor_Logs_DeleteCallLogs = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Logs/DeleteCallLogs',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.DeleteCallLogsRequest,
  proto.ondewo.vtsi.DeleteCallLogsResponse,
  /**
   * @param {!proto.ondewo.vtsi.DeleteCallLogsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.DeleteCallLogsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.DeleteCallLogsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.DeleteCallLogsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.DeleteCallLogsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.LogsClient.prototype.deleteCallLogs =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Logs/DeleteCallLogs',
      request,
      metadata || {},
      methodDescriptor_Logs_DeleteCallLogs,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.DeleteCallLogsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.DeleteCallLogsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.LogsPromiseClient.prototype.deleteCallLogs =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Logs/DeleteCallLogs',
      request,
      metadata || {},
      methodDescriptor_Logs_DeleteCallLogs);
};


module.exports = proto.ondewo.vtsi;

