/**
 * @fileoverview gRPC-Web generated client stub for ondewo.vtsi
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: ondewo/vtsi/softphones.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var ondewo_vtsi_projects_pb = require('../../ondewo/vtsi/projects_pb.js')
const proto = {};
proto.ondewo = {};
proto.ondewo.vtsi = require('./softphones_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ondewo.vtsi.SoftphonesClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ondewo.vtsi.SoftphonesPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.CreateSoftphoneAccountRequest,
 *   !proto.ondewo.vtsi.CreateSoftphoneAccountResponse>}
 */
const methodDescriptor_Softphones_CreateSoftphoneAccount = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/CreateSoftphoneAccount',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.CreateSoftphoneAccountRequest,
  proto.ondewo.vtsi.CreateSoftphoneAccountResponse,
  /**
   * @param {!proto.ondewo.vtsi.CreateSoftphoneAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.CreateSoftphoneAccountResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.CreateSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.CreateSoftphoneAccountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.CreateSoftphoneAccountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.createSoftphoneAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/CreateSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_CreateSoftphoneAccount,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.CreateSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.CreateSoftphoneAccountResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.createSoftphoneAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/CreateSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_CreateSoftphoneAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.GetSoftphoneAccountRequest,
 *   !proto.ondewo.vtsi.SoftphoneAccount>}
 */
const methodDescriptor_Softphones_GetSoftphoneAccount = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/GetSoftphoneAccount',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.GetSoftphoneAccountRequest,
  proto.ondewo.vtsi.SoftphoneAccount,
  /**
   * @param {!proto.ondewo.vtsi.GetSoftphoneAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.SoftphoneAccount.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.GetSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.SoftphoneAccount)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.SoftphoneAccount>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.getSoftphoneAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/GetSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_GetSoftphoneAccount,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.GetSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.SoftphoneAccount>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.getSoftphoneAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/GetSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_GetSoftphoneAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.UpdateSoftphoneAccountRequest,
 *   !proto.ondewo.vtsi.SoftphoneAccount>}
 */
const methodDescriptor_Softphones_UpdateSoftphoneAccount = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/UpdateSoftphoneAccount',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.UpdateSoftphoneAccountRequest,
  proto.ondewo.vtsi.SoftphoneAccount,
  /**
   * @param {!proto.ondewo.vtsi.UpdateSoftphoneAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.SoftphoneAccount.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.UpdateSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.SoftphoneAccount)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.SoftphoneAccount>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.updateSoftphoneAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/UpdateSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_UpdateSoftphoneAccount,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.UpdateSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.SoftphoneAccount>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.updateSoftphoneAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/UpdateSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_UpdateSoftphoneAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.DeleteSoftphoneAccountRequest,
 *   !proto.ondewo.vtsi.DeleteSoftphoneAccountResponse>}
 */
const methodDescriptor_Softphones_DeleteSoftphoneAccount = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/DeleteSoftphoneAccount',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.DeleteSoftphoneAccountRequest,
  proto.ondewo.vtsi.DeleteSoftphoneAccountResponse,
  /**
   * @param {!proto.ondewo.vtsi.DeleteSoftphoneAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.DeleteSoftphoneAccountResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.DeleteSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.DeleteSoftphoneAccountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.DeleteSoftphoneAccountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.deleteSoftphoneAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/DeleteSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_DeleteSoftphoneAccount,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.DeleteSoftphoneAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.DeleteSoftphoneAccountResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.deleteSoftphoneAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/DeleteSoftphoneAccount',
      request,
      metadata || {},
      methodDescriptor_Softphones_DeleteSoftphoneAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ListSoftphoneAccountsRequest,
 *   !proto.ondewo.vtsi.ListSoftphoneAccountsResponse>}
 */
const methodDescriptor_Softphones_ListSoftphoneAccounts = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/ListSoftphoneAccounts',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ListSoftphoneAccountsRequest,
  proto.ondewo.vtsi.ListSoftphoneAccountsResponse,
  /**
   * @param {!proto.ondewo.vtsi.ListSoftphoneAccountsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.ListSoftphoneAccountsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ListSoftphoneAccountsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.ListSoftphoneAccountsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.ListSoftphoneAccountsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.listSoftphoneAccounts =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/ListSoftphoneAccounts',
      request,
      metadata || {},
      methodDescriptor_Softphones_ListSoftphoneAccounts,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ListSoftphoneAccountsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.ListSoftphoneAccountsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.listSoftphoneAccounts =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/ListSoftphoneAccounts',
      request,
      metadata || {},
      methodDescriptor_Softphones_ListSoftphoneAccounts);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.RotateSoftphoneCredentialsRequest,
 *   !proto.ondewo.vtsi.RotateSoftphoneCredentialsResponse>}
 */
const methodDescriptor_Softphones_RotateSoftphoneCredentials = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/RotateSoftphoneCredentials',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.RotateSoftphoneCredentialsRequest,
  proto.ondewo.vtsi.RotateSoftphoneCredentialsResponse,
  /**
   * @param {!proto.ondewo.vtsi.RotateSoftphoneCredentialsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.RotateSoftphoneCredentialsResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.RotateSoftphoneCredentialsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.RotateSoftphoneCredentialsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.RotateSoftphoneCredentialsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.rotateSoftphoneCredentials =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/RotateSoftphoneCredentials',
      request,
      metadata || {},
      methodDescriptor_Softphones_RotateSoftphoneCredentials,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.RotateSoftphoneCredentialsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.RotateSoftphoneCredentialsResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.rotateSoftphoneCredentials =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/RotateSoftphoneCredentials',
      request,
      metadata || {},
      methodDescriptor_Softphones_RotateSoftphoneCredentials);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.ListSoftphoneCertificatesRequest,
 *   !proto.ondewo.vtsi.ListSoftphoneCertificatesResponse>}
 */
const methodDescriptor_Softphones_ListSoftphoneCertificates = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/ListSoftphoneCertificates',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.ListSoftphoneCertificatesRequest,
  proto.ondewo.vtsi.ListSoftphoneCertificatesResponse,
  /**
   * @param {!proto.ondewo.vtsi.ListSoftphoneCertificatesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.ListSoftphoneCertificatesResponse.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.ListSoftphoneCertificatesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.ListSoftphoneCertificatesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.ListSoftphoneCertificatesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.listSoftphoneCertificates =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/ListSoftphoneCertificates',
      request,
      metadata || {},
      methodDescriptor_Softphones_ListSoftphoneCertificates,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.ListSoftphoneCertificatesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.ListSoftphoneCertificatesResponse>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.listSoftphoneCertificates =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/ListSoftphoneCertificates',
      request,
      metadata || {},
      methodDescriptor_Softphones_ListSoftphoneCertificates);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.GetSoftphoneCertificateRequest,
 *   !proto.ondewo.vtsi.SoftphoneCertificate>}
 */
const methodDescriptor_Softphones_GetSoftphoneCertificate = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/GetSoftphoneCertificate',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.GetSoftphoneCertificateRequest,
  proto.ondewo.vtsi.SoftphoneCertificate,
  /**
   * @param {!proto.ondewo.vtsi.GetSoftphoneCertificateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.SoftphoneCertificate.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.GetSoftphoneCertificateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.SoftphoneCertificate)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.SoftphoneCertificate>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.getSoftphoneCertificate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/GetSoftphoneCertificate',
      request,
      metadata || {},
      methodDescriptor_Softphones_GetSoftphoneCertificate,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.GetSoftphoneCertificateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.SoftphoneCertificate>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.getSoftphoneCertificate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/GetSoftphoneCertificate',
      request,
      metadata || {},
      methodDescriptor_Softphones_GetSoftphoneCertificate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.RevokeSoftphoneCertificateRequest,
 *   !proto.ondewo.vtsi.SoftphoneCertificate>}
 */
const methodDescriptor_Softphones_RevokeSoftphoneCertificate = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.RevokeSoftphoneCertificateRequest,
  proto.ondewo.vtsi.SoftphoneCertificate,
  /**
   * @param {!proto.ondewo.vtsi.RevokeSoftphoneCertificateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.SoftphoneCertificate.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.RevokeSoftphoneCertificateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.SoftphoneCertificate)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.SoftphoneCertificate>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.revokeSoftphoneCertificate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate',
      request,
      metadata || {},
      methodDescriptor_Softphones_RevokeSoftphoneCertificate,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.RevokeSoftphoneCertificateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.SoftphoneCertificate>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.revokeSoftphoneCertificate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate',
      request,
      metadata || {},
      methodDescriptor_Softphones_RevokeSoftphoneCertificate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ondewo.vtsi.GetSoftphoneProvisioningRequest,
 *   !proto.ondewo.vtsi.SoftphoneProvisioning>}
 */
const methodDescriptor_Softphones_GetSoftphoneProvisioning = new grpc.web.MethodDescriptor(
  '/ondewo.vtsi.Softphones/GetSoftphoneProvisioning',
  grpc.web.MethodType.UNARY,
  proto.ondewo.vtsi.GetSoftphoneProvisioningRequest,
  proto.ondewo.vtsi.SoftphoneProvisioning,
  /**
   * @param {!proto.ondewo.vtsi.GetSoftphoneProvisioningRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ondewo.vtsi.SoftphoneProvisioning.deserializeBinary
);


/**
 * @param {!proto.ondewo.vtsi.GetSoftphoneProvisioningRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ondewo.vtsi.SoftphoneProvisioning)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ondewo.vtsi.SoftphoneProvisioning>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ondewo.vtsi.SoftphonesClient.prototype.getSoftphoneProvisioning =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/GetSoftphoneProvisioning',
      request,
      metadata || {},
      methodDescriptor_Softphones_GetSoftphoneProvisioning,
      callback);
};


/**
 * @param {!proto.ondewo.vtsi.GetSoftphoneProvisioningRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ondewo.vtsi.SoftphoneProvisioning>}
 *     Promise that resolves to the response
 */
proto.ondewo.vtsi.SoftphonesPromiseClient.prototype.getSoftphoneProvisioning =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ondewo.vtsi.Softphones/GetSoftphoneProvisioning',
      request,
      metadata || {},
      methodDescriptor_Softphones_GetSoftphoneProvisioning);
};


module.exports = proto.ondewo.vtsi;

